const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{FundoSala: 0},
	{Sólido: 0},
	{ArCondicionado: 0},
	{TV: 0},
	{Luz: 0},
	{dvd: 0},
	{Tapete: 0},
	{sofa: 0},
	{hack: 0},
	{vaso1: 0},
	{vaso2: 0},
	{vaso3: 0},
	{Mouse: 0},
	{Teclado: 0},
	{ArCondicionadoNome: 0},
	{FundoCalcular: 0},
	{CalcularGasto: 0},
	{Quantidade: 0},
	{Tempo: 0},
	{textArCond: 0},
	{FecharFundoCalcular: 0},
	{TVNome: 0},
	{LuxNome: 0},
	{VideoGameNome2: 0},
	{DVDNome: 0},
	{Seta: 0},
	{Sala: 0},
	{FundoCozinha: 0},
	{Seta2: 0},
	{Sala2: 0},
	{ArmarioCozinha: 0},
	{Microondas: 0},
	{Geladeira: 0},
	{Fogao: 0},
	{Airfreye: 0},
	{LavaRoupa: 0},
	{MicroondasNome: 0},
	{AirfreyeNome: 0},
	{GeladeiraNome: 0},
	{FogaoNome: 0},
	{LavaRoupaNome: 0},
	{Sprite: 0},
	{InicioSimuladorEnergia: 0},
	{IrSala: 0},
	{IrCozinha: 0},
	{home: 0},
	{Botao: 0},
	{Calcular: 0},
	{Janela: 0},
	{Sprite2: 0},
	{resultadoCalculado: 0},
	{textTV: 0},
	{textHomeTeatcher: 0},
	{textHomeTeatcher2: 0},
	{textMicroOndas: 0},
	{textAirFreye: 0},
	{textGeladeira: 0},
	{textLavaRoupa: 0}
];

self.InstanceType = {
	FundoSala: class extends self.ISpriteInstance {},
	ArCondicionado: class extends self.ISpriteInstance {},
	TV: class extends self.ISpriteInstance {},
	Luz: class extends self.ISpriteInstance {},
	dvd: class extends self.ISpriteInstance {},
	Tapete: class extends self.ISpriteInstance {},
	sofa: class extends self.ISpriteInstance {},
	hack: class extends self.ISpriteInstance {},
	vaso1: class extends self.ISpriteInstance {},
	vaso2: class extends self.ISpriteInstance {},
	vaso3: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	ArCondicionadoNome: class extends self.ITextInstance {},
	FundoCalcular: class extends self.ISpriteInstance {},
	CalcularGasto: class extends self.ITextInstance {},
	Quantidade: class extends self.ITextInstance {},
	Tempo: class extends self.ITextInstance {},
	textArCond: class extends self.ITextInstance {},
	FecharFundoCalcular: class extends self.ISpriteInstance {},
	TVNome: class extends self.ITextInstance {},
	LuxNome: class extends self.ITextInstance {},
	VideoGameNome2: class extends self.ITextInstance {},
	DVDNome: class extends self.ITextInstance {},
	Seta: class extends self.ISpriteInstance {},
	Sala: class extends self.ITextInstance {},
	FundoCozinha: class extends self.ISpriteInstance {},
	Seta2: class extends self.ISpriteInstance {},
	Sala2: class extends self.ITextInstance {},
	ArmarioCozinha: class extends self.ISpriteInstance {},
	Microondas: class extends self.ISpriteInstance {},
	Geladeira: class extends self.ISpriteInstance {},
	Fogao: class extends self.ISpriteInstance {},
	Airfreye: class extends self.ISpriteInstance {},
	LavaRoupa: class extends self.ISpriteInstance {},
	MicroondasNome: class extends self.ITextInstance {},
	AirfreyeNome: class extends self.ITextInstance {},
	GeladeiraNome: class extends self.ITextInstance {},
	FogaoNome: class extends self.ITextInstance {},
	LavaRoupaNome: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	InicioSimuladorEnergia: class extends self.ITextInstance {},
	IrSala: class extends self.ITextInstance {},
	IrCozinha: class extends self.ITextInstance {},
	home: class extends self.ISpriteInstance {},
	Botao: class extends self.ISpriteInstance {},
	Calcular: class extends self.ITextInstance {},
	Janela: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	resultadoCalculado: class extends self.ITextInstance {},
	textTV: class extends self.ITextInstance {},
	textHomeTeatcher: class extends self.ITextInstance {},
	textHomeTeatcher2: class extends self.ITextInstance {},
	textMicroOndas: class extends self.ITextInstance {},
	textAirFreye: class extends self.ITextInstance {},
	textGeladeira: class extends self.ITextInstance {},
	textLavaRoupa: class extends self.ITextInstance {}
}